/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import javax.swing.JButton;

/**
 *
 * @author William
 */
public class FrmSecretaria extends javax.swing.JFrame {

    /**
     * Creates new form FrmSecretaria
     */
    public FrmSecretaria() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        btnFechar = new javax.swing.JButton();
        jPanelConsultas = new javax.swing.JPanel();
        btnAgendarConsulta = new javax.swing.JButton();
        btnConsultasAgendadas = new javax.swing.JButton();
        jPanelPacientes = new javax.swing.JPanel();
        btnPacientesCadastrados = new javax.swing.JButton();
        btnCadastrarPaciente = new javax.swing.JButton();
        jPanelRelatorios = new javax.swing.JPanel();
        btnRelatorioConsultas = new javax.swing.JButton();
        jPanelMensagens = new javax.swing.JPanel();
        btnEnviarMensagens = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Secretária");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblTitulo.setText("Saúde & Cia - Secretária");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, -1, -1));

        btnFechar.setBackground(new java.awt.Color(255, 153, 153));
        btnFechar.setText("Fechar");
        btnFechar.setBorderPainted(false);
        btnFechar.setFocusPainted(false);
        getContentPane().add(btnFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, -1, -1));

        jPanelConsultas.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "Gerenciar Consultas", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        btnAgendarConsulta.setBackground(new java.awt.Color(153, 255, 153));
        btnAgendarConsulta.setText("Agendar Consulta");
        btnAgendarConsulta.setBorder(null);
        btnAgendarConsulta.setBorderPainted(false);
        btnAgendarConsulta.setFocusPainted(false);
        btnAgendarConsulta.setMaximumSize(new java.awt.Dimension(137, 23));
        btnAgendarConsulta.setMinimumSize(new java.awt.Dimension(137, 23));
        btnAgendarConsulta.setPreferredSize(new java.awt.Dimension(137, 23));

        btnConsultasAgendadas.setBackground(new java.awt.Color(204, 204, 255));
        btnConsultasAgendadas.setText("Consultas Agendadas");
        btnConsultasAgendadas.setBorder(null);
        btnConsultasAgendadas.setBorderPainted(false);
        btnConsultasAgendadas.setFocusPainted(false);

        javax.swing.GroupLayout jPanelConsultasLayout = new javax.swing.GroupLayout(jPanelConsultas);
        jPanelConsultas.setLayout(jPanelConsultasLayout);
        jPanelConsultasLayout.setHorizontalGroup(
            jPanelConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsultasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConsultasAgendadas, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgendarConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelConsultasLayout.setVerticalGroup(
            jPanelConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsultasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAgendarConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConsultasAgendadas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 190, 130));

        jPanelPacientes.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "Gerenciar Pacientes", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        btnPacientesCadastrados.setBackground(new java.awt.Color(204, 204, 255));
        btnPacientesCadastrados.setText("Pacientes Cadastrados");
        btnPacientesCadastrados.setBorder(null);
        btnPacientesCadastrados.setBorderPainted(false);
        btnPacientesCadastrados.setFocusPainted(false);

        btnCadastrarPaciente.setBackground(new java.awt.Color(153, 255, 153));
        btnCadastrarPaciente.setText("Cadastrar Paciente");
        btnCadastrarPaciente.setBorder(null);
        btnCadastrarPaciente.setBorderPainted(false);
        btnCadastrarPaciente.setFocusPainted(false);
        btnCadastrarPaciente.setMaximumSize(new java.awt.Dimension(143, 23));
        btnCadastrarPaciente.setMinimumSize(new java.awt.Dimension(143, 23));
        btnCadastrarPaciente.setPreferredSize(new java.awt.Dimension(143, 23));

        javax.swing.GroupLayout jPanelPacientesLayout = new javax.swing.GroupLayout(jPanelPacientes);
        jPanelPacientes.setLayout(jPanelPacientesLayout);
        jPanelPacientesLayout.setHorizontalGroup(
            jPanelPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPacientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCadastrarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPacientesCadastrados, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelPacientesLayout.setVerticalGroup(
            jPanelPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPacientesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCadastrarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnPacientesCadastrados, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanelPacientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 210, 130));

        jPanelRelatorios.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "Relatórios"));

        btnRelatorioConsultas.setBackground(new java.awt.Color(204, 204, 255));
        btnRelatorioConsultas.setText("Relatório de Consultas");
        btnRelatorioConsultas.setBorderPainted(false);
        btnRelatorioConsultas.setFocusPainted(false);
        btnRelatorioConsultas.setMaximumSize(new java.awt.Dimension(143, 23));
        btnRelatorioConsultas.setMinimumSize(new java.awt.Dimension(143, 23));
        btnRelatorioConsultas.setPreferredSize(new java.awt.Dimension(143, 23));

        javax.swing.GroupLayout jPanelRelatoriosLayout = new javax.swing.GroupLayout(jPanelRelatorios);
        jPanelRelatorios.setLayout(jPanelRelatoriosLayout);
        jPanelRelatoriosLayout.setHorizontalGroup(
            jPanelRelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRelatoriosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRelatorioConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelRelatoriosLayout.setVerticalGroup(
            jPanelRelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRelatoriosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRelatorioConsultas, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanelRelatorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 210, 80));

        jPanelMensagens.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "Mensagens"));

        btnEnviarMensagens.setBackground(new java.awt.Color(204, 204, 255));
        btnEnviarMensagens.setText("Enviar Mensagens");
        btnEnviarMensagens.setBorder(null);
        btnEnviarMensagens.setBorderPainted(false);
        btnEnviarMensagens.setFocusPainted(false);
        btnEnviarMensagens.setMaximumSize(new java.awt.Dimension(137, 23));
        btnEnviarMensagens.setMinimumSize(new java.awt.Dimension(137, 23));
        btnEnviarMensagens.setPreferredSize(new java.awt.Dimension(137, 23));

        javax.swing.GroupLayout jPanelMensagensLayout = new javax.swing.GroupLayout(jPanelMensagens);
        jPanelMensagens.setLayout(jPanelMensagensLayout);
        jPanelMensagensLayout.setHorizontalGroup(
            jPanelMensagensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMensagensLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEnviarMensagens, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelMensagensLayout.setVerticalGroup(
            jPanelMensagensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMensagensLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEnviarMensagens, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanelMensagens, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 190, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSecretaria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgendarConsulta;
    private javax.swing.JButton btnCadastrarPaciente;
    private javax.swing.JButton btnConsultasAgendadas;
    private javax.swing.JButton btnEnviarMensagens;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnPacientesCadastrados;
    private javax.swing.JButton btnRelatorioConsultas;
    private javax.swing.JPanel jPanelConsultas;
    private javax.swing.JPanel jPanelMensagens;
    private javax.swing.JPanel jPanelPacientes;
    private javax.swing.JPanel jPanelRelatorios;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnAgendarConsulta() {
        return btnAgendarConsulta;
    }

    public JButton getBtnCadastrarPaciente() {
        return btnCadastrarPaciente;
    }

    public JButton getBtnConsultasAgendadas() {
        return btnConsultasAgendadas;
    }

    public JButton getBtnPacientesCadastrados() {
        return btnPacientesCadastrados;
    }

    public JButton getBtnFechar() {
        return btnFechar;
    }

    public JButton getBtnRelatorioConsultas() {
        return btnRelatorioConsultas;
    }

    public JButton getBtnEnviarMensagens() {
        return btnEnviarMensagens;
    }

    

}
